### ISSUE TITLE
Mappings in variables don't seem to work

### ISSUE THREAD

**Issue by dimitarvdimitrov** [getapid/apid-cli#133]
### Context
when two configs are merged, mappings variables aren't always properly merged

### To reproduce
try to load two files from a directory - `apid -c /tmp/dir/`

#### `/tmp/dir/f1.yml`:
```yaml
variables:
  mapping1:
    var1: True
    var2: '123'
transactions:
- id: "1234"
  steps:
  - id: 'non-empty'
    request:
      method: GET
      endpoint: "https://google.com/{{ var.mapping1.var2 }}"
      body: ""
```

#### `/tmp/dir/f2.yml`
```yaml
variables:
  mapping1:
    var1: 123
    var4: '4'
    var5: '5'
transactions:
- id: a
  steps:
  - id: '1'
    request:
      method: GET
      endpoint: "https://google.com"
      body: ""
```

the values inside `mapping1` aren't properly merged 

### Expected behavior
everything works

### Observed behavior
```
1234:
    FAIL non-empty

         request: GET https://google.com/ 
         errors:
             prepare:
                interpolating step endpoint: var.mapping1.var2: can't deal with this type map[interface {}]interface {}
            
a:
    OK   1
successful transactions: 1/2
failed transactions:     1/2
```

### Output of `apid version`
`APId 0.1.3`
